spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/codeduels
    username: dev
    password: dev
  jpa:
      hibernate:
       ddl-auto: update
      show-sql: true
  data:
      redis:
          host: localhost
          port: 6379
  cloud:
      aws:
          credentials:
              access-key: ${AWS_ACCESS_KEY_ID}
              secret-key: ${AWS_SECRET_ACCESS_KEY}
          region:
              static: eu-central-1

jwt:
  secret: 5294Wn8A6yM8OfbSAE2yvmh8DArjTaStcR2CpK5oq7d
  access-expiration-ms: 900000        # 15 min
  refresh-expiration-ms: 604800000    # 7 days
logging:
  level:
    com.codeduels: DEBUG

app:

  cache:
      test-cases-ttl-minutes: 60
  sqs:
      submission-queue: codeduels-submission
  s3:
      bucket: codeduels-testcases
  internal:
      secret: ${INTERNAL_API_SECRET:lambdaSecretTest}
  frontend:
    url: http://localhost:5732
  avatar:
    base-url: https://api.dicebear.com/9.x/fun-emoji/svg/
  judge0:
    api:
      base-url: http://localhost:2358
      host: judge0-ce.p.rapidapi.com
      key: abfd28b9fbmsh0cf30ad7e62ff74p199ba0jsn38023c8c561f